version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: myredis
    ports:
      - 6379:6379

  urlshortener:
    build: .
    container_name: urlshortener
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
